//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DdfGuide.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DdfGuide.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!--[if IE 7 ]&gt;    &lt;html lang=&quot;de&quot; class=&quot;no-js ie ie7 ltie8 ltie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8 ]&gt;    &lt;html lang=&quot;de&quot; class=&quot;no-js ie ie8 ltie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 9 ]&gt;    &lt;html lang=&quot;de&quot; class=&quot;no-js ie ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if (gt IE 9)|!(IE)]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;de&quot; class=&quot;no-js no-ie&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GefahrAusDemAll {
            get {
                return ResourceManager.GetString("GefahrAusDemAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kometen rasen auf die Erde zu und riesige Meteoriten stürzen vom Himmel. Das zumindest könnte passieren, wenn die Erfindung des genialen Professors in falsche Hände gerät. Den drei ??? bleibt nicht viel Zeit für ihren gefährlichen Auftrag. Der Countdown läuft und dann taucht auch noch ihr Erzfeind auf....
        /// </summary>
        internal static string GefahrAusDemAllDescription {
            get {
                return ResourceManager.GetString("GefahrAusDemAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html public &quot;-//w3c//dtd html 4.0 transitional//en&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///   &lt;meta name=&quot;Author&quot; content=&quot;Detlev&quot;&gt;
        ///   &lt;meta name=&quot;GENERATOR&quot; content=&quot;Mozilla/4.78 [de] (Windows NT 5.0; U) [Netscape]&quot;&gt;
        ///   &lt;title&gt;Der Super-Papagei (H&amp;ouml;rspiel)&lt;/title&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/css/rbcom.css&quot;&gt;
        ///   &lt;script language=&quot;JavaScript1.1&quot; src=&quot;/js/functions.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///   &lt;meta name=&quot;ro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RockyBeachUndDerSuperPapagei {
            get {
                return ResourceManager.GetString("RockyBeachUndDerSuperPapagei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der neueste Auftrag an die drei Detektive hört sich recht harmlos an: sie sollen einen entflogenen Papagei suchen. Doch kaum beginnen sie mit ihren Nachforschungen, da scheinen sich plötzlich noch einige andere Leute sehr für diesen Papagei zu interessieren. Vielleicht deshalb, weil er lateinische Sprüche zitieren kann? Aber bald geht es nicht mehr nur um einen, sondern um sieben Papageien - und alle sieben führen höchst seltsame Reden. Ob da nicht eine geheime Botschaft hintersteckt? Jedenfalls sind auch e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UndDerSuperPapageiDescription {
            get {
                return ResourceManager.GetString("UndDerSuperPapageiDescription", resourceCulture);
            }
        }
    }
}
